spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin123!@#
  redis:
    host: localhost
    port: 6379
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true #test용 데이터베이스 데이터 생성
    properties:
      format-sql: true
      dialect: .org.hibernate.dialect.MySQL8Dialect
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
    defer-datasource-initialization: true
    open-in-view: false
  datasource:
    url: jdbc:mysql://localhost:3306/delivery?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${SPRING_DATA_SOURCE_USER}
    password: ${SPRING_DATA_SOURCE_PASSWORD}

  h2.console.enabled: true
  sql.init.mode: always
  thymeleaf:
    check-template-location: true
    prefix: classpath:/templates/

springdoc:
  model-and-view-allowed: true

token:
  secret:
    key: SpringBootJWTHelperTokenSecretKeyValue123!@#
  access-token:
    plus-hour: 4
  refresh-token:
    plus-hour: 12