server:
  port: 9090

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: user-service # 유저 open-api
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/open-api/**
          filters:
            - RewritePath=/user-service(?<segment>/?.*), $\{segment}
            - ServicePublicApiFilter
        - id: account-service # 스토어 login
          uri: lb://ACCOUNT-SERVICE
          predicates:
            - Path=/account-service/login
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/account-service(?<segment>/?.*), $\{segment}
            - ServicePublicApiFilter
        - id: store-admin-service # 스토어 open-api
          uri: lb://STORE-ADMIN-SERVICE
          predicates:
            - Path=/store-admin-service/open-api/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/store-admin-service(?<segment>/?.*), $\{segment}
            - ServicePublicApiFilter
        - id: store-admin-service # 스토어 api
          uri: lb://STORE-ADMIN-SERVICE
          predicates:
            - Path=/store-admin-service/api/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/store-admin-service(?<segment>/?.*), $\{segment}
            - ServicePrivateApiFilter # 인증 필터