server:
  port: 9090

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: public-service-api #이름
          uri: http://localhost:8080 #api 서버 주소 lb://USER-SERVICE
          predicates:
            - Path=/service-api/open-api/**
          filters:
            - RewritePath=/service-api(?<segment>/?.*), $\{segment}
            - ServicePublicApiFilter

        - id: public-store-admin-service #이름
          uri: http://localhost:8081 #api 서버 주소 lb://STORE-ADMIN-SERVICE
          predicates:
            #- Path=/store-admin-service/open-api/**
            - Path=/public-store-admin/**
          filters:
            - RewritePath=/public-store-admin(?<segment>/?.*), $\{segment}
            - ServicePublicApiFilter
#        - id: public-takeout
#          uri: http://localhost:8083
#          predicates:
#            - Path=/service-takeout/api/take-out/**
#          filters:
#            - RewritePath=/service-takeout(?<segment>/?.*), $\{segment}
#            - ServicePublicApiFilter