#management.endpoints.web.exposure.include: "*"
server:
  port: 8081 #0

spring:
  application:
    name: store-admin-service

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin123!@#
  jpa:
    show-sql: true
    properties:
      format-sql: true
      dialect: .org.hibernate.dialect.MySQL8Dialect
      hibernate.format_sql: true
    defer-datasource-initialization: true
    open-in-view: false
    hibernate:
      ddl-auto: validate
  thymeleaf:
    check-template-location: true
    prefix: classpath:/templates/
    enabled: true
    #suffix: .html
  datasource:
    url: jdbc:mysql://localhost:3306/delivery?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${SPRING_DATA_SOURCE_USER}
    password: ${SPRING_DATA_SOURCE_PASSWORD}
  sql.init.mode: always
  devtools:
    livereload:
      port: 35730
  thymeleaf3:
    decoupled-logic: true

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
    fetch-registry: true
    register-with-eureka: true


springdoc:
  model-and-view-allowed: true